defs: -profile test step updates -monodevelop-database needs md from trunk to build/make tarballs
conf:
-sunos-10-sparc: ajorg set up a new machine
-suse-101-ppc use this faster box for a jail

rpm_defs:
-olive filelist update
-update mono filelist

collect_and_gen_reports:
-make sure webalizer is installed

config.py:
-run sunos-10-sparc and suse-101-ppc bots by default

svn path=/trunk/release/; revision=104928

diff --git a/website/download_stats/collect_and_gen_reports b/website/download_stats/collect_and_gen_reports
--- a/website/download_stats/collect_and_gen_reports
+++ b/website/download_stats/collect_and_gen_reports
@@ -6,6 +6,13 @@
 
 # Note: webalizer expects to see these in order... it doesn't like the urls out of order
 
+which webalizer > /dev/null 2>&1
+
+if [ $? -ne 0 ] ; then
+	echo "webalizer not found.  Exiting..."
+	exit 1
+fi
+
 # check for fastzolver (speeds up reverse dns lookups)
 which fastzolver > /dev/null 2>&1
 
