The script as found on the cygwin buildbot machine
svn path=/trunk/release/; revision=43751

diff --git a/buildbot/scripts/build b/buildbot/scripts/build
--- a/buildbot/scripts/build
+++ b/buildbot/scripts/build
@@ -5,14 +5,20 @@
 
 rm -f /tmp/buildflag-$USER-`hostname`
 cd mono
-echo "Calling autogen.sh --with-preview=yes --prefix=/mono"
-sh autogen.sh --with-preview=yes --prefix=$prefix || { echo "errors"; exit 1; }
 
-echo "Calling make"
-make MCS_FLAGS='-debug -v' || { echo "errors"; exit 1; }
-
-echo "Calling make install"
-make install || { echo "error"; exit 1; }
-
+if uname | grep CYGWIN; then
+    echo Windows Build.
+    bash mono-build-w32.sh || { echo error; exit 1 }
+else
+    echo "Calling autogen.sh --with-preview=yes --prefix=/mono"
+    sh autogen.sh --with-preview=yes --prefix=$prefix || { echo "errors"; exit 1; }
+    
+    echo "Calling make"
+    make MCS_FLAGS='-debug -v' || { echo "errors"; exit 1; }
+    
+    echo "Calling make install"
+    make install || { echo "error"; exit 1; }
+fi
+    
 touch /tmp/buildflag-$USER-`hostname`
 
