Changed output during build to include log file before build starts which makes it easier to tail the current log if you want.
Added actual command line to what I say is being run so that the
individual build can be duplicated seperately.

svn path=/trunk/release/; revision=95551

diff --git a/obs/bin/osc-make-all b/obs/bin/osc-make-all
--- a/obs/bin/osc-make-all
+++ b/obs/bin/osc-make-all
@@ -43,11 +43,12 @@ do
    echo 
    echo "#############################################"
    echo "Exicuting the following command:"
-   echo "osc build ${MYDIST} ${SPEC_FILE}"
-   osc build ${I} ${SPEC_FILE} > ${BUILD_LOG} 2>&1
-   if ! (tail -50 $BUILD_LOG | grep -E "/var/tmp/build-root.*/usr/src/(redhat|packages)/.*rpm"); then
-      echo "${MYDIST} build failed, check ${BUILD_LOG}" >> $FAILED_LOG
-      echo_in_red "${MYDIST} build failed, check ${BUILD_LOG}" 
+   echo "osc build --no-verify ${MYDIST} ${SPEC_FILE}"
+   ecbo "Log file: ${BUILD_LOG}"
+   osc build --no-verify ${I} ${SPEC_FILE} > ${BUILD_LOG} 2>&1
+   if ! (tail -50 ${BUILD_LOG} | grep -E "/var/tmp/build-root.*/usr/src/(redhat|packages)/.*rpm"); then
+      echo "${MYDIST} build failed, check ${BUILD_LOG}" >> ${FAILED_LOG}
+      echo_in_red "${MYDIST} build failed"
    else
       echo_in_green "${MYDIST} build succeeded!"
    fi
