Sync branch config with trunk
svn path=/trunk/release/; revision=108110

diff --git a/packaging/defs/mono-branch b/packaging/defs/mono-branch
--- a/packaging/defs/mono-branch
+++ b/packaging/defs/mono-branch
@@ -104,6 +104,9 @@ win_4_i386_ZIP_DEPS=(
         http://internap.dl.sourceforge.net/sourceforge/gnuwin32/zlib-1.2.3-bin.zip
         http://internap.dl.sourceforge.net/sourceforge/gnuwin32/zlib-1.2.3-lib.zip
 
+	# Used to generate .def files (not needed yet)
+	#http://primates.ximian.com/~wberrier/windows-installer/pexports/pexports-0.43-mono.zip
+
 )
 
 sunos_8_sparc_ZIP_DEPS=(
@@ -147,6 +150,7 @@ macos_10_ppc_ZIP_DEPS=(
 	http://primates.ximian.com/~wberrier/macos/deps/ppc/glib-2.14.1-0.macos10.novell.ppc.zip
 	http://primates.ximian.com/~wberrier/macos/deps/ppc/pkg-config-0.22-0.macos10.novell.ppc.zip
 	http://primates.ximian.com/~wberrier/macos/deps/ppc/gettext-0.16.1-0.macos10.novell.ppc.zip
+	http://primates.ximian.com/~wberrier/macos/deps/ppc/sqlite-3.5.7-0.macos10.novell.ppc.zip
 )
 
 macos_10_x86_ZIP_DEPS=(
@@ -154,6 +158,7 @@ macos_10_x86_ZIP_DEPS=(
 	http://primates.ximian.com/~wberrier/macos/deps/x86/glib-2.14.1-0.macos10.novell.x86.zip
 	http://primates.ximian.com/~wberrier/macos/deps/x86/pkg-config-0.22-0.macos10.novell.x86.zip
 	http://primates.ximian.com/~wberrier/macos/deps/x86/gettext-0.16.1-0.macos10.novell.x86.zip
+	http://primates.ximian.com/~wberrier/macos/deps/ppc/sqlite-3.5.7-0.macos10.novell.x86.zip
 )
 
 sunos_8_sparc_ZIP_BUILD () {
@@ -313,12 +318,7 @@ RELEASE_PATH=(
 make_dist () {
 	. /etc/profile
 	./autogen.sh
-	#if [ $HEAD_or_RELEASE == "HEAD" ] ; then
-        #        make dist-zip MCS=mcs RESGEN=resgen
-        #else
-                make dist-bzip2 MCS=mcs RESGEN=resgen
-        #fi
-
+	make dist-bzip2 MCS=mcs RESGEN=resgen
 }
 
 POSTBUILD_TEST_NAME1="test-runtime"
@@ -350,47 +350,446 @@ POSTBUILD_TEST3 () {
 	fi
 }
 
-POSTBUILD_TEST_NAME4="test-profiles"
+POSTBUILD_TEST_NAME4="test-cas"
 POSTBUILD_TEST4 () {
-	#TEST_HARNESS_VERBOSE=1
-	#export TEST_HARNESS_VERBOSE
-	#echo "Skipping..."
-	cd runtime
-	$make_path -k check
-
-}
-
-# TODO:
-# Separate 1.0 and 2.0 profiles into different steps
-POSTBUILD_TEST_NAME5="test-cas"
-POSTBUILD_TEST5 () {
 	cd mono/tests/cas
 	$make_path -k test
 }
 
-POSTBUILD_TEST_NAME6="test-swf"
+POSTBUILD_TEST_NAME5="tests-verify"
+POSTBUILD_TEST5 () {
+	cd runtime
+	$make_path mcs-compileall
+}
+
+POSTBUILD_TEST_NAME6="test-compiler-1.0"
 POSTBUILD_TEST6 () {
-	#TEST_HARNESS_VERBOSE=1
-	#export TEST_HARNESS_VERBOSE
+	cd mcs/tests
+	$make_path run-test
+}
+
+POSTBUILD_TEST_NAME7="test-compiler-2.0"
+POSTBUILD_TEST7 () {
+	cd mcs/tests
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME8="test-compiler-errors-1.0"
+POSTBUILD_TEST8 () {
+	cd mcs/errors
+	$make_path run-test
+}
+
+POSTBUILD_TEST_NAME9="test-compiler-errors-2.0"
+POSTBUILD_TEST9 () {
+	cd mcs/errors
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME10="test-corlib-1.0"
+POSTBUILD_TEST10 () {
+
+	cd mcs/class/corlib
+	$make_path run-test
+}
+
+POSTBUILD_TEST_NAME11="test-corlib-2.0"
+POSTBUILD_TEST11 () {
+	cd mcs/class/corlib
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME12="test-System-1.0"
+POSTBUILD_TEST12 () {
+	cd mcs/class/System
+	$make_path run-test
+}
+
+POSTBUILD_TEST_NAME13="test-System-2.0"
+POSTBUILD_TEST13 () {
+	cd mcs/class/System
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME14="test-System_XML-1.0"
+POSTBUILD_TEST14 () {
+	cd mcs/class/System.XML
+	$make_path run-test
+}
+
+POSTBUILD_TEST_NAME15="test-System_XML-2.0"
+POSTBUILD_TEST15 () {
+	cd mcs/class/System.XML
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME16="test-Mono_Security-1.0"
+POSTBUILD_TEST16 () {
+	cd mcs/class/Mono.Security
+	$make_path run-test
+}
+
+POSTBUILD_TEST_NAME17="test-Mono_Security-2.0"
+POSTBUILD_TEST17 () {
+	cd mcs/class/Mono.Security
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME18="test-System_Security-1.0"
+POSTBUILD_TEST18 () {
+	cd mcs/class/System.Security
+	$make_path run-test
+}
+
+POSTBUILD_TEST_NAME19="test-System_Security-2.0"
+POSTBUILD_TEST19 () {
+	cd mcs/class/System.Security
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME20="test-System_Drawing-1.0"
+POSTBUILD_TEST20 () {
 	DISPLAY=x32-linux-1.mono.lab.novell.com:1
 	export DISPLAY
 
-	failure=0
-
 	cd mcs/class/System.Drawing
-	$make_path run-test || failure=1
-	$make_path run-test PROFILE=net_2_0 || failure=1
-
-	cd ../Managed.Windows.Forms
-	$make_path run-test || failure=1
-	$make_path run-test PROFILE=net_2_0 || failure=1
-
-	exit $failure
-
+	$make_path run-test
 }
 
-POSTBUILD_TEST_NAME7="test-ondotnet"
-POSTBUILD_TEST7 () {
+POSTBUILD_TEST_NAME21="test-System_Drawing-2.0"
+POSTBUILD_TEST21 () {
+	DISPLAY=x32-linux-1.mono.lab.novell.com:1
+	export DISPLAY
+
+	cd mcs/class/System.Drawing
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME22="test-Windows_Forms-1.0"
+POSTBUILD_TEST22 () {
+	DISPLAY=x32-linux-1.mono.lab.novell.com:1
+	export DISPLAY
+
+	cd mcs/class/Managed.Windows.Forms
+	$make_path run-test
+}
+
+POSTBUILD_TEST_NAME23="test-Windows_Forms-2.0"
+POSTBUILD_TEST23 () {
+	DISPLAY=x32-linux-1.mono.lab.novell.com:1
+	export DISPLAY
+
+	cd mcs/class/Managed.Windows.Forms
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME24="test-System_Data-1.0"
+POSTBUILD_TEST24 () {
+	cd mcs/class/System.Data
+	$make_path run-test
+}
+
+POSTBUILD_TEST_NAME25="test-System_Data-2.0"
+POSTBUILD_TEST25 () {
+	cd mcs/class/System.Data
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME26="test-Mono_Data_Sqlite-1.0"
+POSTBUILD_TEST26 () {
+	cd mcs/class/Mono.Data.Sqlite
+	$make_path run-test
+}
+
+POSTBUILD_TEST_NAME27="test-Mono_Data_Sqlite-2.0"
+POSTBUILD_TEST27 () {
+	cd mcs/class/Mono.Data.Sqlite
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME28="test-Mono_Data_SqliteClient-1.0"
+POSTBUILD_TEST28 () {
+	cd mcs/class/Mono.Data.SqliteClient
+	$make_path run-test
+}
+
+POSTBUILD_TEST_NAME29="test-Mono_Data_SqliteClient-2.0"
+POSTBUILD_TEST29 () {
+	cd mcs/class/Mono.Data.SqliteClient
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME30="test-System_Data_OracleClient-1.0"
+POSTBUILD_TEST30 () {
+	cd mcs/class/System.Data.OracleClient
+	$make_path run-test
+}
+
+POSTBUILD_TEST_NAME31="test-System_Data_OracleClient-2.0"
+POSTBUILD_TEST31 () {
+	cd mcs/class/System.Data.OracleClient
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME32="test-System_Design-1.0"
+POSTBUILD_TEST32 () {
+	cd mcs/class/System.Design
+	$make_path run-test
+}
+
+POSTBUILD_TEST_NAME33="test-System_Design-2.0"
+POSTBUILD_TEST33 () {
+	cd mcs/class/System.Design
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME34="test-Mono_Posix-1.0"
+POSTBUILD_TEST34 () {
+	cd mcs/class/Mono.Posix
+	$make_path run-test
+}
+
+POSTBUILD_TEST_NAME35="test-Mono_Posix-2.0"
+POSTBUILD_TEST35 () {
+	cd mcs/class/Mono.Posix
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME36="test-System_Web-1.0"
+POSTBUILD_TEST36 () {
+	cd mcs/class/System.Web
+	$make_path run-test
+}
+
+POSTBUILD_TEST_NAME37="test-System_Web-2.0"
+POSTBUILD_TEST37 () {
+	cd mcs/class/System.Web
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME38="test-System_Web_Services-1.0"
+POSTBUILD_TEST38 () {
+	cd mcs/class/System.Web.Services
+	$make_path run-test
+}
+
+POSTBUILD_TEST_NAME39="test-System_Web_Services-2.0"
+POSTBUILD_TEST39 () {
+	cd mcs/class/System.Web.Services
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME40="test-System_Runtime_SFS-1.0"
+POSTBUILD_TEST40 () {
+	cd mcs/class/System.Runtime.Serialization.Formatters.Soap
+	$make_path run-test
+}
+
+POSTBUILD_TEST_NAME41="test-System_Runtime_SFS-2.0"
+POSTBUILD_TEST41 () {
+	cd mcs/class/System.Runtime.Serialization.Formatters.Soap
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME42="test-System_Runtime_Remoting-1.0"
+POSTBUILD_TEST42 () {
+	cd mcs/class/System.Runtime.Remoting
+	$make_path run-test
+}
+
+POSTBUILD_TEST_NAME43="test-System_Runtime_Remoting-2.0"
+POSTBUILD_TEST43 () {
+	cd mcs/class/System.Runtime.Remoting
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME44="test-Cscompmgd-1.0"
+POSTBUILD_TEST44 () {
+	cd mcs/class/Cscompmgd
+	$make_path run-test
+}
+
+POSTBUILD_TEST_NAME45="test-Cscompmgd-2.0"
+POSTBUILD_TEST45 () {
+	cd mcs/class/Cscompmgd
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME46="test-Commons_Xml_Relaxng-1.0"
+POSTBUILD_TEST46 () {
+	cd mcs/class/Commons.Xml.Relaxng
+	$make_path run-test
+}
+
+POSTBUILD_TEST_NAME47="test-Commons_Xml_Relaxng-2.0"
+POSTBUILD_TEST47 () {
+	cd mcs/class/Commons.Xml.Relaxng
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME48="test-System_Messaging-1.0"
+POSTBUILD_TEST48 () {
+	cd mcs/class/System.Messaging
+	$make_path run-test
+}
+
+POSTBUILD_TEST_NAME49="test-System_Messaging-2.0"
+POSTBUILD_TEST49 () {
+	cd mcs/class/System.Messaging
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME50="test-System_ServiceProcess-1.0"
+POSTBUILD_TEST50 () {
+	cd mcs/class/System.ServiceProcess
+	$make_path run-test
+}
+
+POSTBUILD_TEST_NAME51="test-System_ServiceProcess-2.0"
+POSTBUILD_TEST51 () {
+	cd mcs/class/System.ServiceProcess
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME52="test-Microsoft_JScript-1.0"
+POSTBUILD_TEST52 () {
+	cd mcs/class/Microsoft.JScript
+	$make_path run-test
+}
+
+POSTBUILD_TEST_NAME53="test-Microsoft_JScript-2.0"
+POSTBUILD_TEST53 () {
+	cd mcs/class/Microsoft.JScript
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME54="test-I18N_CJK-1.0"
+POSTBUILD_TEST54 () {
+	cd mcs/class/I18N/CJK
+	$make_path run-test
+}
+
+POSTBUILD_TEST_NAME55="test-I18N_CJK-2.0"
+POSTBUILD_TEST55 () {
+	cd mcs/class/I18N/CJK
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME56="test-I18N_West-1.0"
+POSTBUILD_TEST56 () {
+	cd mcs/class/I18N/West
+	$make_path run-test
+}
+
+POSTBUILD_TEST_NAME57="test-I18N_West-2.0"
+POSTBUILD_TEST57 () {
+	cd mcs/class/I18N/West
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME58="test-System_DirectoryServices-1.0"
+POSTBUILD_TEST58 () {
+	cd mcs/class/System.DirectoryServices
+	$make_path run-test
+}
+
+POSTBUILD_TEST_NAME59="test-System_DirectoryServices-2.0"
+POSTBUILD_TEST59 () {
+	cd mcs/class/System.DirectoryServices
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME60="test-Microsoft_Build_Engine-2.0"
+POSTBUILD_TEST60 () {
+	cd mcs/class/Microsoft.Build.Engine
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME61="test-Microsoft_Build_Framework-2.0"
+POSTBUILD_TEST61 () {
+	cd mcs/class/Microsoft.Build.Framework
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME62="test-Microsoft_Build_Tasks-2.0"
+POSTBUILD_TEST62 () {
+	cd mcs/class/Microsoft.Build.Tasks
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME63="test-Microsoft_Build_Utilities-2.0"
+POSTBUILD_TEST63 () {
+	cd mcs/class/Microsoft.Build.Utilities
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME64="test-Mono_C5-2.0"
+POSTBUILD_TEST64 () {
+	cd mcs/class/Mono.C5
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME65="test-System_Configuration-2.0"
+POSTBUILD_TEST65 () {
+	cd mcs/class/System.Configuration
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME66="test-System_Transactions-2.0"
+POSTBUILD_TEST66 () {
+	cd mcs/class/System.Transactions
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME67="test-System_Web_Extensions-2.0"
+POSTBUILD_TEST67 () {
+	cd mcs/class/System.Web.Extensions
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME68="test-System_Web_Extensions-3.5"
+POSTBUILD_TEST68 () {
+	cd mcs/class/System.Web.Extensions
+	$make_path run-test PROFILE=net_3_5
+}
+
+POSTBUILD_TEST_NAME69="test-System_Core-3.5"
+POSTBUILD_TEST69 () {
+	cd mcs/class/System.Core
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME70="test-System_Xml_Linq-3.5"
+POSTBUILD_TEST70 () {
+	cd mcs/class/System.Xml.Linq
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME71="test-System_Data_DSE-3.5"
+POSTBUILD_TEST71 () {
+	cd mcs/class/System.Data.DataSetExtensions
+	$make_path run-test PROFILE=net_2_0
+}
+
+POSTBUILD_TEST_NAME72="test-results"
+POSTBUILD_TEST72 () {
+
+	mkdir -p test_results
+        target=$build_location/steps/test-results
+        mkdir -p $target
+
+	# Collect xml files
+	for i in $(find . -name "TestResult*.xml") ; do
+		cp $i test_results/$(basename $(dirname $i))-$(basename $i)
+	done
+
+	cp -a mcs/tools/nunitreport/Media $target
+
+	MONO_PATH="mcs/class/lib/net_2_0:$MONO_PATH" runtime/mono-wrapper mcs/tools/nunitreport/nunitreport.exe test_results $target/index.html
+}
+
+POSTBUILD_TEST_NAME73="test-ondotnet"
+POSTBUILD_TEST73 () {
 	if test x$DISTRO = xwin-4-i386 ; then
 
 		OLD_PATH=$PATH
@@ -490,10 +889,14 @@ POSTBUILD_STEP1 () {
 
         # todo: wget these out of subversion
         wget --tries=1 --timeout=10 http://primates.ximian.com/~wberrier/class_status/deploy.tar.bz2
-	wget --tries=1 --timeout=10 http://anonsvn.mono-project.com/source/trunk/olive/status/mono-api.xsl
+        wget --tries=1 --timeout=10 http://anonsvn.mono-project.com/source/trunk/olive/status/mono-api.xsl
 
         tar -zxf masterinfos-$VERSION.tar.gz
         tar -jxf deploy.tar.bz2
+
+        # update content that frequently changes from subversion
+        wget --tries=1 --timeout=10 http://anonsvn.mono-project.com/source/trunk/mono/web/web/deploy/cm/cormissing.css -O deploy/cm/cormissing.css
+        wget --tries=1 --timeout=10 http://anonsvn.mono-project.com/source/trunk/mono/web/web/deploy/cm/cormissing.js -O deploy/cm/cormissing.js
 
         mkdir infos
         mkdir src
@@ -551,10 +954,16 @@ CLEAN_UP () {
 
 	rm -Rf	/tmp/mcs*	/var/tmp/mcs*
 
+	# clean up asp.net (linux and solaris)
+	rm -Rf  /tmp/*-temp-aspnet-0 /var/tmp/*-temp-aspnet-0
+
 	# These tend to get left around on win32... ?
 	if test x$DISTRO = xwin-4-i386 ; then
-		/home/builder/bin/Process.exe   -k mono.exe || true
+		taskkill /F /T /IM mono.exe || true
 	fi
 
 }
+
+
+
 
