defs: -add some test steps
do-zip-build: add support for zip source 'tarballs'

First commit of scheduler

monobuild.py: add running time

Rest of changes are support changes for the build scheduler


svn path=/trunk/release/; revision=58828

diff --git a/packaging/do-zip-build b/packaging/do-zip-build
--- a/packaging/do-zip-build
+++ b/packaging/do-zip-build
@@ -12,26 +12,42 @@ mkdir scratch && cd scratch 		|| exit 1
 
 mv ../$package .
 mv ../*.tar.gz .
+mv ../*.zip .
 mv ../*.patch .
 
 tarball=`ls *.tar.gz`
-component_name_ver=${tarball//\.tar\.gz/}
-arch=${distro#*-*-}
+use_zip=0
 
-if [ -e /usr/local/bin/tar ] ; then
-	# This is for the solaris 8 machine
-	TAR=/usr/local/bin/tar
-elif [ -e /usr/sfw/bin/gtar ] ; then
-	# This is for the solaris 10 box
-	TAR=/usr/sfw/bin/gtar
-else
-	TAR=tar
+if [ x == x$tarball ] ; then
+	tarball=`ls *.zip`
+	use_zip=1
 fi
 
-$TAR -zxf *.tar.gz			|| exit 1
+arch=${distro#*-*-}
 
-# Why wasn't this used? failed unpacking??
-#gzip -dc *.tar.gz | tar -xf -		|| exit 1
+if [ $use_zip -eq 0 ] ; then
+
+	component_name_ver=${tarball//\.tar\.gz/}
+
+	if [ -e /usr/local/bin/tar ] ; then
+		# This is for the solaris 8 machine
+		TAR=/usr/local/bin/tar
+	elif [ -e /usr/sfw/bin/gtar ] ; then
+		# This is for the solaris 10 box
+		TAR=/usr/sfw/bin/gtar
+	else
+		TAR=tar
+	fi
+
+	$TAR -zxf *.tar.gz			|| exit 1
+
+	# Why wasn't this used? failed unpacking??
+	#gzip -dc *.tar.gz | tar -xf -		|| exit 1
+
+else
+	component_name_ver=${tarball//\.zip/}
+	unzip -q *.zip				|| exit 1
+fi
 
 cd $component_name_ver
 
