Updates for 1.1.13 release:
win32 patch is in trunk and 1.1.13 branch, but I didn't want to bump another release
to get it in

now the zip build system will apply patches


svn path=/trunk/release/; revision=55278

diff --git a/packaging/do-zip-build b/packaging/do-zip-build
--- a/packaging/do-zip-build
+++ b/packaging/do-zip-build
@@ -11,22 +11,30 @@ mkdir scratch && cd scratch 		|| exit 1
 
 mv ../$package .
 mv ../*.tar.gz .
+mv ../*.patch .
 
 tarball=`ls *.tar.gz`
 component_name_ver=${tarball//\.tar\.gz/}
 arch=${distro#*-*-}
 
-if [ -e /opt/csw/bin/gtar ] ; then
+if [ -e /usr/local/bin/tar ] ; then
 	# This is for the solaris 8 machine
-	TAR=/opt/csw/bin/gtar
+	TAR=/usr/local/bin/tar
 else
 	TAR=tar
 fi
 
 $TAR -zxf *.tar.gz			|| exit 1
+
+# Why wasn't this used? failed unpacking??
 #gzip -dc *.tar.gz | tar -xf -		|| exit 1
 
 cd $component_name_ver
+
+# Apply patches
+for i in `ls  ../*.patch | sort -n` ; do
+	patch -p1 < $i			|| exit 1
+done
 
 # Load environment for deps
 . /tmp/build_deps/env.sh
