non-rug-based dep installation
svn path=/trunk/release/; revision=43176

diff --git a/packaging/install-deps b/packaging/install-deps
--- a/packaging/install-deps
+++ b/packaging/install-deps
@@ -1,13 +1,44 @@
 #!/bin/sh
 
+. shared-code.sh
+
 TARGET=$1
-
-shift
-
-PACKAGES="$*"
-
+PACKAGE=$2
 . conf/$TARGET
+. defs/$PACKAGE
 
-scp do-install-deps $target_host:$jaildir/tmp
+distro_info $TARGET
 
-./jail-do $TARGET sh -x /tmp/do-install-deps "$PACKAGES"
+DEPS=${MONO_DEPS[@]}
+
+
+RPMS=$i
+
+for i in $DEPS; do
+	. defs/$i
+	
+	get_destroot
+	
+	[ -d packages/$DEST_ROOT/$i/*/ ] || (
+		echo "Could not find $i for $DISTRO (looking in $DEST_ROOT)"
+		exit 1;
+	)
+	
+	VERSION=`ls -d packages/$DEST_ROOT/$i/*/ -t -1 | head -n1`
+	
+	for i in $VERSION/*.rpm; do
+		[[ $i == *.src.rpm ]] && continue
+		
+		RPMS=(${RPMS[@]} $i)
+	done
+done
+
+[ ${#RPMS[@]} -eq 0 ] && exit 0
+
+
+./jail-do $TARGET "sh -x -c 'rm -rf /tmp/install-packages; mkdir -p /tmp/install-packages -m777'"
+
+scp ${RPMS[@]} $target_host:$jaildir/tmp/install-packages
+
+./jail-do $TARGET "sh -x -c 'rpm -Uhv /tmp/install-packages/*.rpm'"
+./jail-do $TARGET "sh -x -c 'rm -rf /tmp/install-packages'"
